[global]
ignore_file = " Makefile.ini, Makefile, configure";
ignore_dir = "demo, .git, tests";

[target#0]
target = "lib/ui";
target_param = "644"
target_user = "swan";
target_group = "swan";
target_dir_param = "755"
target_dir_user = "swan";
target_dir_group = "swan";
