[global]
ignore_file = " Makefile.ini, Makefile, configure, .gitignore, README.md, .travis.yml, install.sh, LICENSE, .gitmodules";
ignore_dir = "demo, .git, tests, test";

[target#0]
target = "";
target_param = "644"
target_user = "swan";
target_group = "swan";
target_dir_param = "755"
target_dir_user = "swan";
target_dir_group = "swan";
